version: '3'
services:
  spring-boot-dockerize:
    image: spring-boot-docker
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/jhooq-springboot-container
    ports:
      - "9090:9090"